#!/usr/bin/env ruby

require_relative './app'
require_relative './options_processor'

state = { books: [], people: [] }

puts 'Welcome to the School library App'

print 'Please create a username: '
user_name = gets.chomp

puts "\n"
puts "Welcome #{user_name}! Please choose an options by entering a number: "

def run_app
  puts '1 - List all books'
  puts '2 - List all people'
  puts '3 - Create a new person'
  puts '4 - Create a new book'
  puts '5 - Create a new rental'
  puts '6 - List all rentals for a given id'
  puts '7 - Exit'

  puts ''
  print 'Please enter your selection: '
  gets.chomp
end

def main(data)
  app = OptionsProcessor.new
  app.get_user_options(run_app, data)
  main(data)
end

main(state)
