#!/usr/bin/env ruby

require_relative './enums'

class App

    include Enumerables
    attr_accessor :user_name, :people, :books
    def initialize(books = [], people = [])
        @name = user_name
        @books = books
        @people = people
    end

    puts 'Welcome to the School library management system'

    puts 'Please create a username: '
    user_name = gets.chomp
    
    puts "\n"
    puts "Welcome #{user_name}! Please choose an options by entering a number:"

    def run_app
        puts '1 - List all books'
        puts '2 - List all people'
        puts '3 - Create a new person'
        puts '4 - Create a new book'
        puts '5 - Create a new rental'
        puts '6 - List all rentals for a given id'
        puts '7 - Exit'
        
        options = gets.chomp.to_i
        puts "\n"

        case options
        when 1
            list_all_books(@books)
        when 2
            list_all_people(people)
        when 3
            create_person(people)
        when 4
            create_book(books)
        else
            
        end

    end
end


def main
    app = App.new()
    app.run_app()

    main()
end

main()